controllers_front:
    resource: ../../src/Controller/Front
    type: annotation
    name_prefix: front_

controllers_admin:
    resource: ../../src/Controller/BackOffice
    type: annotation
    prefix: /admin
    name_prefix: admin_

controllers:
    resource: ../../src/Controller
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
